cities= {
    'cb':['цб','центробанк'],
    'moskva': ['москв','мск','столиц'],
    'sankt-peterburg':['спб','питер','петербург'],
    'novosibirsk':['нск','новосиб'],
    'volgograd':['волгоград','влг'],
    'voronezh':['воронеж'],
    'vladivostok':['владивосток','владик'],
    'ekaterinburg':['екб','екатеринбург'],
    'irkutsk':['иркутск'],
    'izhevsk':['ижевск'],
    'kazan~':['казан'],
    'krasnodar':['краснодар'],
    'krasnoyarsk':['красноярск'],
    'kaliningrad':['калининград'],
    'kirov':['киров'],
    'nizhniy_novgorod':['нижний','новгород','нино'],
    'novokuznetssk':['новокузнецк'],
    'omsk':['омск'],
    'orenburg':['оренбург'],
    'perm~':['перм'],
    'rostov-na-donu':['ростов'],
    'samara':['самар'],
    'saratov':['саратов'],
    'tyumen~':['тюмен'],
    'tomsk':['томск'],
    'ufa':['уф'],
    'habarovsk':['хабаровск'],
    'chelyabinsk':['челябинск'],
    'yaroslavl~':['ярославл'],
    'murmansk':['мурманск']
            }

currencies= {
    'usd': ['доллар','usd','бакс','$'],
    'eur': ['евро','eur'],
    'gbp': ['фунт','gbp'],
    'jpy': ['йен','jpy'],
    'cny': ['юан','cny']
                }
